stage("Create docker image"){
podTemplate(label: 'nodejs',cloud: 'openshift'){
    // containers: [containerTemplate(name: 'docker', image: 'docker:dind', ttyEnabled: true, command: 'cat')],
    // volumes: [hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock')]) {
    node('nodejs') {
        stage('do some Docker work') {
            container('jnlp') {
                sh "echo test"
            withCredentials([[$class: 'UsernamePasswordMultiBinding',
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_HUB_USER',
                    passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
                // sleep 100
                git 'https://github.com/SchSeba/test-jenkins'
                kubernetes.image().withName("sebassch/example").build().fromPath(".")
                sh "docker login -u ${env.DOCKER_HUB_USER} -p ${env.DOCKER_HUB_PASSWORD} "
                sh "docker push sebassch/example"
                }
            }
        }
    }
}
}
stage("Openshift Deploy")
node {
    openshiftDeploy(namespace: 'seba', deploymentConfig: 'nodejs-seba')
}