// node('nodejs') {
//   stage 'build'
//   openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
//   stage 'deploy'
//   openshiftDeploy(deploymentConfig: 'nodejs-ex')
// }

podTemplate(label: 'nodejs',cloud: 'openshift'){

  node('nodejs') {
    stage('Build a Maven project') {
      git 'https://github.com/SchSeba/test-jenkins'
      container('jnlp') {
          sh 'npm install' 
      }
    }
  }
}