// node('nodejs') {
//   stage 'build'
//   openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
//   stage 'deploy'
//   openshiftDeploy(deploymentConfig: 'nodejs-ex')
// }

podTemplate(label: 'nodejs',cloud: 'openshift'){

  node('nodejs') {
    stage('Build a Maven project') {
      git 'https://github.com/SchSeba/test-jenkins'
      container('jnlp') {
          sh 'npm install' 
      }
    }
  }
}

node {
    git 'https://github.com/SchSeba/test-jenkins'
    kubernetes.image().withName("sebassch/example").build().fromPath(".")
    kubernetes.image().withName("sebassch/example").push().toRegistry()
}

podTemplate(label: 'nodejs',cloud: 'openshift') {
            node('nodejs') {
                stage('do some Docker work') {
                container('jnlp') {

                withCredentials([[$class: 'UsernamePasswordMultiBinding',
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_HUB_USER',
                        passwordVariable: 'DOCKER_HUB_PASSWORD']]) {

                    sh """
                        docker pull ubuntu
                        docker tag ubuntu ${env.DOCKER_HUB_USER}/ubuntu:${env.BUILD_NUMBER}
                        """
                    sh "docker login -u ${env.DOCKER_HUB_USER} -p ${env.DOCKER_HUB_PASSWORD} "
                    sh "docker push ${env.DOCKER_HUB_USER}/ubuntu:${env.BUILD_NUMBER} "
                }
            }
        }
            }

}